workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      groups:
        - keystore_credentials
      vars:
        GRADLE_OPTS: "-Xmx4096m"
      java: 17

    scripts:
      - name: "Step 1 - Unzip packaged project (if needed)"
        script: |
          if [ -f project.zip ]; then
            echo "Unzipping project.zip..."
            unzip -o project.zip -d .
          else
            echo "No project.zip found, skipping unzip."
          fi

      - name: "Step 2 - Ensure Gradle Wrapper exists"
        script: |
          if [ ! -f "./gradlew" ]; then
            echo "Gradle wrapper not found, generating..."
            gradle wrapper
          else
            echo "Gradle wrapper already exists."
          fi
          chmod +x gradlew

      - name: "Step 3 - Clean Project"
        script: |
          ./gradlew clean

      - name: "Step 4 - Build Debug APK and AAB"
        script: |
          ./gradlew assembleDebug bundleDebug

    artifacts:
      - build/outputs/**/*.apk
      - build/outputs/**/*.aab
