workflows:
  android-workflow:
    name: Build OM Enterprises Android APK
    scripts:
      - name: "Unzip and move project"
        script: |
          unzip -o om_project.zip -d workspace_unzipped
          mv workspace_unzipped/* .
          ls -la
      - name: "Build APK"
        script: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
            ./gradlew clean assembleDebug --stacktrace --no-daemon
          else
            echo "gradlew not found, using system gradle"
            gradle clean assembleDebug --stacktrace --no-daemon
          fi
    artifacts:
      - app/build/outputs/**/*.apk
