
workflows:
  android-workflow:
    name: Android Build
    environment:
      java: 17
    scripts:
      - name: Detect project root
        script: |
          echo "=== Detect project root ==="
          # look for settings.gradle in repo
          PROJECT_FILE=$(find . -maxdepth 3 -type f -name "settings.gradle" | head -n 1)
          if [ -z "$PROJECT_FILE" ]; then
            echo "❌ ERROR: No settings.gradle found"
            exit 1
          fi
          PROJECT_DIR=$(dirname "$PROJECT_FILE")
          echo "✅ Found project root: $PROJECT_DIR"
          # export for later steps
          echo "PROJECT_DIR=$PROJECT_DIR" >> $CM_ENV_FILE

      - name: Ensure AndroidX flags
        script: |
          echo "=== Ensure AndroidX flags ==="
          echo "Using PROJECT_DIR=$PROJECT_DIR"
          GP="$PROJECT_DIR/gradle.properties"
          mkdir -p "$(dirname "$GP")"
          touch "$GP"
          grep -qxF "android.useAndroidX=true" "$GP" || echo "android.useAndroidX=true" >> "$GP"
          grep -qxF "android.enableJetifier=true" "$GP" || echo "android.enableJetifier=true" >> "$GP"
          cat "$GP"

      - name: Generate Gradle wrapper if missing
        script: |
          cd "$PROJECT_DIR"
          if [ ! -f ./gradlew ]; then
            echo "No gradlew found, generating wrapper..."
            gradle wrapper --gradle-version 8.5
          fi
          chmod +x gradlew

      - name: Build APK
        script: |
          cd "$PROJECT_DIR"
          ./gradlew clean assembleDebug --no-daemon --stacktrace

    artifacts:
      - "**/app/build/outputs/**/*.apk"
      - "**/app/build/outputs/**/*.aab"
