workflows:
  android-workflow:
    name: Build Android App
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PROJECT_DIR: "app"
    scripts:
      - name: "step 1: clean project"
        script: |
          echo "Cleaning project..."
          rm -rf build
      - name: Step 2: Check Gradle wrapper
        script: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
            echo "Using project gradlew"
          else
            echo "No gradlew found. Exiting..."
            exit 1
          fi
      - name: Step 3: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
