workflows:
  android-workflow:
    name: Build OM Enterprises Android APK
    scripts:
      - name: "Step 1: Unzip packaged project"
        script: |
          echo "Unzipping om_project.zip..."
          unzip -o om_project.zip -d workspace_unzipped
          cd workspace_unzipped
          ls -la
      - name: "Step 2: Build with Gradle"
        script: |
          cd workspace_unzipped
          if [ -f ./gradlew ]; then
            echo "Using gradlew wrapper"
            chmod +x ./gradlew
            ./gradlew clean assembleDebug
          else
            echo "gradlew not found, using system gradle"
            gradle clean assembleDebug
          fi
    artifacts:
      - workspace_unzipped/app/build/outputs/**/*.apk
