workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      java: 17
      vars:
        GRADLE_VERSION: "8.5"
    scripts:
      - name: Step 1: Unzip packaged project (if needed)
        script: |
          if [ -f project.zip ]; then
            echo "Unzipping project.zip..."
            unzip -o project.zip -d .
          else
            echo "No project.zip found, skipping unzip."
          fi

      - name: Step 2: Ensure Gradle wrapper exists
        script: |
          echo "Checking for gradlew..."
          if [ ! -f "./gradlew" ]; then
            echo "gradlew not found. Generating wrapper with Gradle $GRADLE_VERSION"
            gradle wrapper --gradle-version $GRADLE_VERSION
            chmod +x gradlew
          else
            echo "gradlew already exists."
          fi

      - name: Step 3: Build Debug APK and AAB
        script: |
          ./gradlew clean
          ./gradlew assembleDebug
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - pateljalpesh28@gmail.com
